service: momor-api
frameworkVersion: '3'


plugins:
  - serverless-offline
  - serverless-plugin-cloudwatch-dashboard
  - serverless-deployment-bucket
  - serverless-dotenv-plugin
  - serverless-plugin-typescript

provider:
  name: aws
  runtime: nodejs18.x
  region: ap-northeast-2
  stage: prod
  architecture: arm64
  deploymentBucket:
    name: momor-api-v1-dev
  environment:
    SERVER_PORT: ${.env:SERVER_PORT}
    DB_PORT: ${.env:DB_PORT}
    DB_HOST: ${.env:DB_HOST}
    DB_USER: ${.env:DB_USER}
    DB_PASSWORD: ${.env:DB_PASSWORD}
    DB_DATABASE: ${.env:DB_DATABASE}

functions:
  main:
    handler: src/handler.handler
    events:
      - http:
          method: get
          path: /health
      - http:
          method: post
          path: /auth/login
          cors:
            origins: 
              - https://localhost:3000
            # origins: '*'
            allowCredentials: true
      - http:
          method: get
          path: /auth/logout
          cors:
            origins: 
              - https://localhost:3000
            # origins: '*'
            allowCredentials: true
      - http:
          method: post
          path: /users
          cors:
            origins: 
              - https://localhost:3000
            # origins: '*'
            allowCredentials: true
      - http:
          method: post
          path: /users/{userNo}/accounts
          cors:
            origins: 
              - https://localhost:3000
            # origins: '*'
            allowCredentials: true
      - http:
          method: get
          path: /users/{userNo}/accounts
          cors:
            origins: 
              - https://localhost:3000
            # origins: '*'
            allowCredentials: true
      - http:
          method: delete
          path: /users/{userNo}/accounts/{accountNo}
          cors:
            origins: 
              - https://localhost:3000
            allowCredentials: true
      - http:
          method: get
          path: /accounts/asset-types
          cors: false
      - http:
          method: get
          path: /accounts/banks
          cors: false
      - http:
          method: post
          path: /cards/companies
          cors:
            origins: 
              - https://localhost:3000
            allowCredentials: true
      - http:
          method: get
          path: /cards/companies
          cors:
            origins: 
              - https://localhost:3000
            allowCredentials: true
      - http:
          method: post
          path: /users/{userNo}/cards
          cors:
            origins: 
              - https://localhost:3000
            allowCredentials: true
      - http:
          method: get
          path: /users/{userNo}/cards
          cors:
            origins: 
              - https://localhost:3000
            allowCredentials: true
      - http:
          method: delete
          path: /users/{userId}/cards/{cardId}
          cors:
            origins: 
              - https://localhost:3000
            allowCredentials: true
        

custom:
  enable_optimize:
    local: false
  serverless-offline:
    httpPort: 3000 # 로컬 포트
    lambdaPort: 3001 # 람다 포트

  # Enable source maps
  tsConfig: tsconfig.json
  # Enable automatic TypeScript compilation
  webpack:
    webpackConfig: './webpack.config.js'
    includeModules: true